export default {
  data() {
    return {
      multipleSelection: [],
      tableData: {
        loading: false,
        emptyImg: true,
        options: {
          selection: true, //多选框
          index: null, //序号
          headTool: false, //开启头部工具栏
          refreshBtn: false, //开启表格头部刷新按钮
          downloadBtn: false, //开启表格头部下载按钮
          headerCellClassName: this.cellClass,
          // entityName:"StockOutDetail",
        }, //序号和复选框
        rows: [], //表数据
        columns: [
          // {
          //   label: "",
          //   type: "selection",
          //   show: true,
          // },
          // {
          //   label: "行号",
          //   width: "80",
          //   type: "index",
          //   show: true,
          // },
          // {
          //   prop: "isSample",
          //   label: "是否只出样件",
          //   width: "100",
          //   renderSlot: "true",
          //   show: true,
          // },
          // {
          //   prop: "lack",
          //   label: "是否缺货",
          //   minWidth: "110",
          //   sortable: false,
          //   show: true,
          //   renderSlot: true,
          // },
          {
            prop: "warehouse",
            label: "域编码",
            minWidth: "200",
            sortable: false,
            show: true,
          },
          {
            prop: "productCode",
            label: "零件号",
            minWidth: "",
            sortable: false,
            show: true,
          },
          {
            prop: "productName",
            label: "零件名称",
            minWidth: "",
            sortable: false,
            show: true,
          },
          {
            prop: "productName",
            label: "零件名称",
            minWidth: "",
            sortable: false,
            show: true,
          },
          {
            prop: "productStatusDesc",
            label: "零件状态",
            minWidth: "100",
            sortable: false,
            show: true,
          },
          {
            prop: "productTypeDesc",
            label: "零件类型",
            minWidth: "100",
            sortable: false,
            show: true,
          },
          {
            prop: "suppcust",
            label: "供应商/客户",
            minWidth: "100",
            sortable: false,
            show: true,
          },
          {
            prop: "planner",
            label: "计划员",
            minWidth: "",
            sortable: false,
            show: true,
          },
          {
            prop: "city",
            label: "交付城市",
            minWidth: "",
            sortable: false,
            show: true,
          },
          {
            prop: "family",
            label: "DWH零件家族",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "dwhvmi",
            label: "DWH是否VMI零件",
            minWidth: "",
            sortable: false,
            show: true,
          },
          {
            prop: "dwhmodel",
            label: "是否参与DWH模型推荐",
            minWidth: "",
            sortable: false,
            show: true,
          },
          {
            prop: "dwhsmkt",
            label: "DWH是否为超市物流",
            minWidth: "",
            sortable: false,
            show: true,
          },
          {
            prop: "stockdirect",
            label: "横放/竖放",
            minWidth: "110",
            sortable: false,
            show: true,
          },
          {
            prop: "saftyqty",
            label: "安全库存数量",
            minWidth: "110",
            sortable: false,
            show: true,
          },
          {
            prop: "allamount",
            label: "箱标包数量",
            minWidth: "110",
            sortable: false,
            show: true,
          },
          {
            prop: "packagingRate",
            label: "零件数量/托",
            minWidth: "110",
            sortable: false,
            show: true,
          },
          {
            prop: "skunetwet",
            label: "零件净重量（KG）",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "skugrosswet",
            label: "零件毛重量（KG）",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "palletlayer",
            label: "包装层数/托",
            minWidth: "100",
            sortable: false,
            show: true,
            renderSlot: "true",
            // fixed: "right",
          },
          {
            prop: "layerqty",
            label: "包装数量/层",
            minWidth: "",
            sortable: false,
            show: true,
          },
          {
            prop: "palletboxqty",
            label: "包装箱数/托",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "palletgoodsheight",
            label: "托盘含货高（mm）",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "stacking",
            label: "托盘是否允许堆垛",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "stackingqty",
            label: "托盘堆垛数量",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "mixpart",
            label: "是否允许零件混托",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "mixpackage",
            label: "不同包装主数据是否允许混托",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "layerfufill",
            label: "是否填空箱满层",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "country",
            label: "原产国",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "boxcode",
            label: "包装箱件号",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "boxname",
            label: "包装箱名称",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "boxdesc",
            label: "包装箱描述",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "allUnit",
            label: "包装箱单位",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "packagetypeDesc",
            label: "包装类型",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "boxnetwet",
            label: "包装箱净重（kg）",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "boxgrosswet",
            label: "包装箱毛重（KG）",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "boxlength",
            label: "包装箱外径尺寸（mm）长",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "boxwidth",
            label: "包装箱外径尺寸（mm）宽",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "boxheight",
            label: "包装箱外径尺寸（mm）高",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "boxwet",
            label: "包装总重量(KG)",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "usepallet",
            label: "是否使用托盘",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "palletcode",
            label: "托盘件号",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "palletname",
            label: "托盘名称",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "palletdesc",
            label: "托盘描述",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "palletunit",
            label: "托盘单位",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "pallettype",
            label: "托盘型",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "palletnetwet",
            label: "托盘净重（kg）",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "palletwet",
            label: "整托重量（KG）",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "palletlength",
            label: "托盘外径尺寸（mm）长",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "palletwidth",
            label: "托盘外径尺寸（mm）宽",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "palletheight",
            label: "托盘外径尺寸（mm）高",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "palletvol",
            label: "每托含货体积（cbm）",
            minWidth: "150",
            sortable: false,
            show: true,
          },
          {
            prop: "aS246",
            label: "托盘尺寸是否符合AS246",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "palletvolpercent",
            label: "周转箱返空体积率（%）",
            width: 180,
            sortable: false,
            show: true,
          },
          {
            prop: "dangergoods",
            label: "危险品运输",
            minWidth: "150",
            sortable: false,
            show: true,
          },
        ], //表头
        operates: [], //表格里面的操作按钮
        tableHeightDiff: 350,
      },
      paginations: {
        page: 1, //当前位于那页面
        total: 10, //总数
        limit: 20, //一页显示多少条
        pagetionShow: false,
      },
      boxNoForm: {
        dialogFormVisible: false,
        title: "指定箱号",
        row: {},
      },
    };
  },
};
